# Bu workflow, master branch'ine yapılan her push işleminde otomatik olarak
# tarih ve build numarasına göre bir etiket oluşturur ve release yayınlar.
name: Build and Release with Automatic Tag

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    # Release oluşturma işlemi için yazma (write) izni gereklidir.
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # YENİ ADIM: Otomatik olarak etiket ismini oluşturur.
      - name: Generate tag name
        id: generate_tag
        run: echo "tag_name=v$(date +'%Y.%m.%d')-${{ github.run_number }}" >> $GITHUB_OUTPUT

      # GÜNCELLENMİŞ ADIM: Oluşturulan etiketi kullanarak release yayınlar.
      - name: Create Release and Upload JAR
        uses: softprops/action-gh-release@v2
        with:
          # Önceki adımda oluşturduğumuz etiketi burada kullanıyoruz.
          tag_name: ${{ steps.generate_tag.outputs.tag_name }}
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
