# Bu workflow, Maven ile bir Java projesini derler ve oluşan JAR dosyasını bir GitHub Release olarak yayınlar.
name: Build and Release JAR

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Create Release and Upload JAR
        uses: softprops/action-gh-release@v2
        with:
          # Bu kısım, 'target' klasöründeki tüm .jar dosyalarını release'e ekler.
          # pom.xml dosyanızda tek bir JAR üretildiğinden emin olun.
          files: target/*.jar
        env:
          # Bu token, release oluşturmak için gereklidir ve GitHub tarafından otomatik olarak sağlanır.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
